---
- name: Ensure incus projects cluster facts
  ansible.builtin.command:
    cmd: incus cluster show {{ inventory_hostname }}
  register: incus_projects_cluster_info_state
  failed_when: false
  changed_when: false
  become: true
