---
- name: Ensure incus projects
  ansible.builtin.include_tasks: project.yml
  vars:
    incus_projects_project_name: "{{ incus_projects_project.name }}"
    incus_projects_project_state: "{{ incus_projects_project.state | default(incus_projects_state) }}"
    incus_projects_project_socket_path: "{{ incus_projects_socket_path }}"
    incus_projects_project_url: "{{ incus_projects_url | default(omit) }}"
    incus_projects_project_client_cert: "{{ incus_projects_client_cert | default(omit) }}"
    incus_projects_project_client_key: "{{ incus_projects_client_key | default(omit) }}"
    incus_projects_project_server_cert: "{{ incus_projects_server_cert | default(omit) }}"
    incus_projects_project_token: "{{ incus_projects_token | default(omit) }}"
    incus_projects_project_validate_certs: "{{ incus_projects_validate_certs }}"
  no_log: "{{ incus_projects_client_key is defined or incus_projects_token is defined }}"
  loop: "{{ incus_projects }}"
  loop_control:
    label: "{{ incus_projects_project_name }}"
    loop_var: incus_projects_project
