---
argument_specs:
  main:
    short_description: Ensure Incus images.
    description:
      - Ensure Incus images.
    examples: |
      - name: Ensure incus images
        hosts: incus
        tasks:
          - name: Ensure incus images
            ansible.builtin.import_role:
              name: damex.incus.incus_images
            vars:
              incus_images:
                - source: images:debian/13
                  alias: debian13
                - source: images:ubuntu/24.04
                  alias: ubuntu2404
                  type: virtual-machine
                  auto_update: true
                - source: docker:library/nginx
                  alias: nginx
    options:
      incus_images:
        type: list
        elements: dict
        description: Images to ensure.
        options:
          source:
            required: true
            type: str
            description: Remote source identifier.
          type:
            type: str
            description: Image instance type.
            choices:
              - container
              - virtual-machine
          alias:
            required: true
            type: str
            description: Local image alias.
          copy_aliases:
            type: bool
            description: Source alias copying.
          auto_update:
            type: bool
            description: Automatic image update on new build.
          public:
            type: bool
            description: Unauthenticated user image access.
          source_server:
            type: str
            description: Remote image server URL.
          source_protocol:
            type: str
            description: Remote image server protocol.
            choices:
              - simplestreams
              - incus
              - oci
          project:
            type: str
            description: Incus project scope.
          state:
            type: str
            description: Image desired state.
            choices:
              - present
              - absent
      incus_images_socket_path:
        type: path
        description: Incus Unix socket path.
      incus_images_url:
        type: str
        description: Incus server API URL.
      incus_images_client_cert:
        type: str
        description: Client certificate content for API authentication.
      incus_images_client_key:
        type: str
        description: Client key content for API authentication.
      incus_images_server_cert:
        type: str
        description: Server certificate content for API verification.
      incus_images_client_cert_path:
        type: path
        description: TLS client certificate path for API authentication.
      incus_images_client_key_path:
        type: path
        description: TLS client key path for API authentication.
      incus_images_server_cert_path:
        type: path
        description: TLS server certificate path for API verification.
      incus_images_token:
        type: str
        description: Incus API authentication token.
      incus_images_validate_certs:
        type: bool
        description: TLS certificate validation.
      incus_images_type:
        type: str
        description: Image instance type.
        choices:
          - container
          - virtual-machine
      incus_images_copy_aliases:
        type: bool
        description: Source alias copying.
      incus_images_auto_update:
        type: bool
        description: Automatic image update on new build.
      incus_images_public:
        type: bool
        description: Unauthenticated user image access.
      incus_images_source_server:
        type: str
        description: Remote image server URL.
      incus_images_source_protocol:
        type: str
        description: Remote image server protocol.
        choices:
          - simplestreams
          - incus
      incus_images_project:
        type: str
        description: Incus project scope.
      incus_images_state:
        type: str
        description: Images desired state.
        choices:
          - present
          - absent
