---
argument_specs:
  main:
    options:
      incus_images:
        type: list
        elements: dict
        options:
          source:
            required: true
            type: str
          type:
            type: str
            choices:
              - container
              - virtual-machine
          alias:
            required: true
            type: str
          copy_aliases:
            type: bool
          project:
            type: str
          state:
            type: str
            choices:
              - present
              - absent
      incus_images_socket_path:
        type: path
      incus_images_url:
        type: str
      incus_images_client_cert:
        type: path
      incus_images_client_key:
        type: path
        no_log: true
      incus_images_server_cert:
        type: path
      incus_images_token:
        type: str
        no_log: true
      incus_images_validate_certs:
        type: bool
      incus_images_type:
        type: str
        choices:
          - container
          - virtual-machine
      incus_images_copy_aliases:
        type: bool
      incus_images_project:
        type: str
      incus_images_state:
        type: str
        choices:
          - present
          - absent
