---
argument_specs:
  main:
    short_description: Ensure Incus.
    description:
      - Ensure Incus.
    examples: |
      - name: Ensure incus
        hosts: incus
        tasks:
          - name: Ensure incus
            ansible.builtin.import_role:
              name: damex.incus.incus

      - name: Ensure incus with specific version
        hosts: incus
        tasks:
          - name: Ensure incus with specific version
            ansible.builtin.import_role:
              name: damex.incus.incus
            vars:
              incus_package_name: incus-lts
              incus_package_version: 6.0.4-zabbly1
    options:
      incus_package_name:
        type: str
        description: Incus server package name.
      incus_package_version:
        type: str
        description: Incus server package version.
      incus_package_state:
        type: str
        description: Incus server package state.
        choices:
          - present
          - absent
      incus_service_name:
        type: str
        description: Incus systemd service name.
      incus_service_state:
        type: str
        description: Incus systemd service state.
        choices:
          - started
          - stopped
      incus_socket_name:
        type: str
        description: Incus systemd socket unit name.
      incus_socket_state:
        type: str
        description: Incus systemd socket unit state.
        choices:
          - started
          - stopped
      incus_socket_path:
        type: str
        description: Incus Unix socket file path.
      incus_user_service_name:
        type: str
        description: Incus user systemd service name.
      incus_user_service_state:
        type: str
        description: Incus user systemd service state.
        choices:
          - started
          - stopped
      incus_user_socket_name:
        type: str
        description: Incus user systemd socket unit name.
      incus_user_socket_state:
        type: str
        description: Incus user systemd socket unit state.
        choices:
          - started
          - stopped
      incus_user_socket_path:
        type: str
        description: Incus user Unix socket file path.
      incus_apt_preference_name:
        type: str
        description: APT pinning preference file name.
      incus_apt_preference_pin:
        type: str
        description: APT pin specification.
      incus_apt_preference_pin_priority:
        type: int
        description: APT pin priority value.
