---
argument_specs:
  main:
    short_description: Ensure Incus.
    description:
      - Ensure Incus.
    examples: |
      - name: Ensure incus
        hosts: incus
        tasks:
          - name: Ensure incus
            ansible.builtin.import_role:
              name: damex.incus.incus

      - name: Ensure incus with specific version
        hosts: incus
        tasks:
          - name: Ensure incus with specific version
            ansible.builtin.import_role:
              name: damex.incus.incus
            vars:
              incus_package_name: incus-lts
              incus_package_version: 6.0.4-zabbly1
    options:
      incus_package_name:
        type: str
        description: Name of the Incus server package.
      incus_package_version:
        type: str
        description: Version of the Incus server package to install.
      incus_package_state:
        type: str
        description: Desired state of the Incus server package.
        choices:
          - present
          - absent
      incus_service_name:
        type: str
        description: Name of the Incus systemd service.
      incus_service_state:
        type: str
        description: Desired state of the Incus systemd service.
        choices:
          - started
          - stopped
      incus_socket_name:
        type: str
        description: Name of the Incus systemd socket unit.
      incus_socket_state:
        type: str
        description: Desired state of the Incus systemd socket unit.
        choices:
          - started
          - stopped
      incus_lxcfs_service_name:
        type: str
        description: Name of the Incus LXCFS systemd service.
      incus_lxcfs_service_state:
        type: str
        description: Desired state of the Incus LXCFS systemd service.
        choices:
          - started
          - stopped
      incus_user_service_name:
        type: str
        description: Name of the Incus user systemd service.
      incus_user_service_state:
        type: str
        description: Desired state of the Incus user systemd service.
        choices:
          - started
          - stopped
      incus_user_socket_name:
        type: str
        description: Name of the Incus user systemd socket unit.
      incus_user_socket_state:
        type: str
        description: Desired state of the Incus user systemd socket unit.
        choices:
          - started
          - stopped
      incus_apt_preference_name:
        type: str
        description: Name of the APT pinning preference file.
      incus_apt_preference_pin:
        type: str
        description: APT pin specification for package priority.
      incus_apt_preference_pin_priority:
        type: int
        description: APT pin priority value for the Incus repository.
