---
namespace: damex
name: incus
version: 1.7.3
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
description: incus collection
license_file: LICENSE
tags:
  - incus
  - linux
  - system
dependencies:
  damex.apt: ">=1.4.8"
  damex.yum: ">=1.3.5"
  damex.systemd: ">=2.0.3"
repository: https://github.com/damex/ansible-collections-incus
issues: https://github.com/damex/ansible-collections-incus/issues
