---
- name: Ensure incus repository apt repository {{ incus_repository_apt_repository_name }}
  ansible.builtin.include_role:
    name: damex.apt.apt_repositories
  vars:
    apt_repositories: # noqa: var-naming[no-role-prefix]
      - name: "{{ incus_repository_apt_repository_name }}"
        url: "{{ incus_repository_apt_repository_url }}"
        distribution: "{{ incus_repository_apt_repository_distribution | default(ansible_facts['distribution_release']) }}"
        components: "{{ incus_repository_apt_repository_components }}"
  when: ansible_facts['pkg_mgr'] == "apt"
