---
- name: Ensure incus service restarted on address change
  ansible.builtin.include_role:
    name: damex.systemd.systemd_service
  vars:
    systemd_service_name: incus
    systemd_service_restart_on: "{{ incus_server_restart and incus_server_configuration_state.restart_required }}"
