---
- name: Ensure incus profiles
  ansible.builtin.include_tasks: profile.yml
  vars:
    incus_profiles_profile_name: "{{ incus_profiles_profile.name }}"
    incus_profiles_profile_config: "{{ incus_profiles_profile.config | default(omit) }}"
    incus_profiles_profile_devices: "{{ incus_profiles_profile.devices | default(omit) }}"
    incus_profiles_profile_project: "{{ incus_profiles_profile.project | default(incus_profiles_project) }}"
    incus_profiles_profile_state: "{{ incus_profiles_profile.state | default(incus_profiles_state) }}"
    incus_profiles_profile_socket_path: "{{ incus_profiles_socket_path }}"
    incus_profiles_profile_url: "{{ incus_profiles_url | default(omit) }}"
    incus_profiles_profile_client_cert: "{{ incus_profiles_client_cert | default(omit) }}"
    incus_profiles_profile_client_key: "{{ incus_profiles_client_key | default(omit) }}"
    incus_profiles_profile_server_cert: "{{ incus_profiles_server_cert | default(omit) }}"
    incus_profiles_profile_token: "{{ incus_profiles_token | default(omit) }}"
    incus_profiles_profile_validate_certs: "{{ incus_profiles_validate_certs }}"
  loop: "{{ incus_profiles }}"
  loop_control:
    label: "{{ incus_profiles_profile_name }}"
    loop_var: incus_profiles_profile
