---
argument_specs:
  main:
    short_description: Ensure Incus client.
    description:
      - Ensure Incus client.
    examples: |
      - name: Ensure incus client
        hosts: incus
        tasks:
          - name: Ensure incus client
            ansible.builtin.import_role:
              name: damex.incus.incus_client

      - name: Ensure incus client with remote servers
        hosts: workstations
        tasks:
          - name: Ensure incus client with remote servers
            ansible.builtin.import_role:
              name: damex.incus.incus_client
            vars:
              incus_client_configuration:
                default-remote: local
                remotes:
                  - name: local
                    addr: unix://
                    protocol: incus
                    public: false
                  - name: production
                    addr: https://incus.example.com:8443
                    protocol: incus
                    public: false
    options:
      incus_client_package_name:
        type: str
        description: Incus client package name.
      incus_client_package_state:
        type: str
        description: Incus client package state.
        choices:
          - present
          - absent
      incus_client_apt_preference_name:
        type: str
        description: Incus client APT preference file name.
      incus_client_apt_preference_pin:
        type: str
        description: Incus client APT pin specification.
      incus_client_apt_preference_pin_priority:
        type: int
        description: Incus client APT pin priority.
      incus_client_user:
        type: str
        description: Client configuration files owner.
      incus_client_group:
        type: str
        description: Client configuration files group.
      incus_client_configuration_directory:
        type: path
        description: Incus client configuration directory path.
      incus_client_configuration_file:
        type: path
        description: Incus client configuration file path.
      incus_client_configuration:
        type: dict
        required: true
        description: Incus client configuration.
        options:
          default-remote:
            type: str
            required: true
            description: Default remote name.
          remotes:
            type: list
            elements: dict
            required: true
            description: Remote server definitions.
            options:
              name:
                type: str
                required: true
                description: Remote name.
              addr:
                type: str
                required: true
                description: Remote server address.
              protocol:
                type: str
                required: true
                description: Remote communication protocol.
              public:
                type: bool
                description: Public remote.
          aliases:
            type: dict
            description: Incus client command aliases.
          defaults:
            type: dict
            description: Incus client default settings.
            options:
              list_format:
                type: str
                description: List commands output format.
              console_type:
                type: str
                description: Console type.
              console_spice_command:
                type: str
                description: SPICE console connection command.
