---
- name: Ensure incus cluster groups
  ansible.builtin.include_tasks: cluster_group.yml
  vars:
    incus_cluster_groups_cluster_group_name: "{{ incus_cluster_groups_cluster_group.name }}"
    incus_cluster_groups_cluster_group_state: "{{ incus_cluster_groups_cluster_group.state | default(incus_cluster_groups_state) }}"
    incus_cluster_groups_cluster_group_socket_path: "{{ incus_cluster_groups_socket_path }}"
    incus_cluster_groups_cluster_group_url: "{{ incus_cluster_groups_url | default(omit) }}"
    incus_cluster_groups_cluster_group_client_cert: "{{ incus_cluster_groups_client_cert | default(omit) }}"
    incus_cluster_groups_cluster_group_client_key: "{{ incus_cluster_groups_client_key | default(omit) }}"
    incus_cluster_groups_cluster_group_server_cert: "{{ incus_cluster_groups_server_cert | default(omit) }}"
    incus_cluster_groups_cluster_group_client_cert_path: "{{ incus_cluster_groups_client_cert_path | default(omit) }}"
    incus_cluster_groups_cluster_group_client_key_path: "{{ incus_cluster_groups_client_key_path | default(omit) }}"
    incus_cluster_groups_cluster_group_server_cert_path: "{{ incus_cluster_groups_server_cert_path | default(omit) }}"
    incus_cluster_groups_cluster_group_token: "{{ incus_cluster_groups_token | default(omit) }}"
    incus_cluster_groups_cluster_group_validate_certs: "{{ incus_cluster_groups_validate_certs }}"
  no_log: "{{ incus_cluster_groups_client_key is defined or incus_cluster_groups_token is defined }}"
  loop: "{{ incus_cluster_groups }}"
  loop_control:
    label: "{{ incus_cluster_groups_cluster_group_name }}"
    loop_var: incus_cluster_groups_cluster_group
