---
- name: Ensure incus cluster groups
  tags:
    - incus
    - incus_cluster_groups
  block:
    - name: Ensure incus cluster groups facts
      ansible.builtin.import_tasks: facts.yml
    - name: Ensure incus cluster groups
      ansible.builtin.import_tasks: cluster_groups.yml
