---
- name: Ensure incus storages cluster facts
  damex.incus.incus_cluster_info:
    name: "{{ inventory_hostname }}"
    socket_path: "{{ incus_storages_socket_path }}"
    url: "{{ incus_storages_url | default(omit) }}"
    client_cert: "{{ incus_storages_client_cert | default(omit) }}"
    client_key: "{{ incus_storages_client_key | default(omit) }}"
    server_cert: "{{ incus_storages_server_cert | default(omit) }}"
    token: "{{ incus_storages_token | default(omit) }}"
    validate_certs: "{{ incus_storages_validate_certs }}"
  no_log: "{{ incus_storages_client_key is defined or incus_storages_token is defined }}"
  register: incus_storages_cluster_info_state
  become: true
