---
- name: Ensure incus storage {{ incus_storages_storage_name }}
  damex.incus.incus_storage:
    name: "{{ incus_storages_storage_name }}"
    state: "{{ incus_storages_storage_state }}"
    driver: "{{ incus_storages_storage.driver }}"
    description: "{{ incus_storages_storage_description }}"
    config: "{{ incus_storages_storage.config | default(omit) }}"
    socket_path: "{{ incus_storages_storage_socket_path }}"
    url: "{{ incus_storages_storage_url }}"
    client_cert: "{{ incus_storages_storage_client_cert }}"
    client_key: "{{ incus_storages_storage_client_key }}"
    server_cert: "{{ incus_storages_storage_server_cert }}"
    client_cert_path: "{{ incus_storages_storage_client_cert_path }}"
    client_key_path: "{{ incus_storages_storage_client_key_path }}"
    server_cert_path: "{{ incus_storages_storage_server_cert_path }}"
    token: "{{ incus_storages_storage_token }}"
    validate_certs: "{{ incus_storages_storage_validate_certs }}"
  no_log: "{{ incus_storages_client_key is defined or incus_storages_token is defined or (incus_storages_storage.config is defined and 'truenas.api_key' in incus_storages_storage.config) }}"
  become: true
