---
- name: Ensure incus storage {{ incus_storages_storage_name }}
  when: incus_storages_cluster_info_state.cluster_members | length == 0 or 'database' in incus_storages_cluster_info_state.cluster_members[0].roles
  become: true
  block:
    - name: Ensure incus storage info {{ incus_storages_storage_name }}
      damex.incus.incus_storage_info:
        name: "{{ incus_storages_storage_name }}"
        socket_path: "{{ incus_storages_socket_path }}"
      register: incus_storages_storage_info_state
    - name: Ensure incus storage is created {{ incus_storages_storage_name }}
      ansible.builtin.command:
        cmd: incus storage create {{ incus_storages_storage_name }} {{ incus_storages_storage_driver }}
        stdin: "{{ lookup('ansible.builtin.template', role_path | dirname | dirname + '/templates/storage.j2') }}"
      vars:
        incus_template_config: "{{ incus_storages_storage_config }}"
      changed_when: true
      when:
        - incus_storages_storage_info_state.storage_pools | length == 0
        - incus_storages_storage_state != "absent"
    - name: Ensure incus storage configuration {{ incus_storages_storage_name }}
      ansible.builtin.command:
        cmd: incus storage edit {{ incus_storages_storage_name }}
        stdin: "{{ lookup('ansible.builtin.template', role_path | dirname | dirname + '/templates/storage.j2') }}"
      vars:
        incus_template_config: "{{ incus_storages_storage_config }}"
      changed_when: false
      when:
        - incus_storages_storage_info_state.storage_pools | length > 0
        - incus_storages_storage_state != "absent"
    - name: Ensure incus storage is absent {{ incus_storages_storage_name }}
      ansible.builtin.command:
        cmd: incus storage delete {{ incus_storages_storage_name }}
      changed_when: true
      when:
        - incus_storages_storage_state == "absent"
        - incus_storages_storage_info_state.storage_pools | length > 0
