# -*- coding: utf-8 -*-
# Copyright: Roman Kuzmitskii <ansible@damex.org>
# SPDX-License-Identifier: GPL-3.0-or-later

"""Incus instance config argument spec options."""

from __future__ import annotations

from typing import Any

from ansible_collections.damex.incus.plugins.module_utils.cloud_init import (
    CLOUD_INIT_CONFIG_OPTIONS,
)

__all__ = [
    'INCUS_INSTANCE_CONFIG_OPTIONS',
]

INCUS_INSTANCE_CONFIG_OPTIONS: dict[str, Any] = {
    'limits.cpu': {'type': 'str'},
    'limits.memory': {'type': 'str'},
    'limits.processes': {'type': 'int'},
    'limits.cpu.priority': {'type': 'int'},
    'limits.cpu.allowance': {'type': 'str'},
    'limits.cpu.nodes': {'type': 'str'},
    'limits.disk.priority': {'type': 'int'},
    'limits.network.priority': {'type': 'int'},
    'limits.hugepages.1GB': {'type': 'str'},
    'limits.hugepages.1MB': {'type': 'str'},
    'limits.hugepages.2MB': {'type': 'str'},
    'limits.hugepages.64KB': {'type': 'str'},
    'limits.memory.enforce': {'type': 'str'},
    'limits.memory.hotplug': {'type': 'str'},
    'limits.memory.hugepages': {'type': 'bool'},
    'limits.memory.oom_priority': {'type': 'int'},
    'limits.memory.swap': {'type': 'str'},
    'limits.memory.swap.priority': {'type': 'int'},
    'boot.autostart': {'type': 'bool'},
    'boot.autostart.delay': {'type': 'int'},
    'boot.autostart.priority': {'type': 'int'},
    'boot.autorestart': {'type': 'bool'},
    'boot.host_shutdown_action': {'type': 'str'},
    'boot.host_shutdown_timeout': {'type': 'int'},
    'boot.stop.priority': {'type': 'int'},
    'security.privileged': {'type': 'bool'},
    'security.nesting': {'type': 'bool'},
    'security.agent.metrics': {'type': 'bool'},
    'security.bpffs.delegate_attachs': {'type': 'str'},
    'security.bpffs.delegate_cmds': {'type': 'str'},
    'security.bpffs.delegate_maps': {'type': 'str'},
    'security.bpffs.delegate_progs': {'type': 'str'},
    'security.bpffs.path': {'type': 'str'},
    'security.csm': {'type': 'bool'},
    'security.guestapi': {'type': 'bool'},
    'security.guestapi.images': {'type': 'bool'},
    'security.idmap.base': {'type': 'int'},
    'security.idmap.isolated': {'type': 'bool'},
    'security.idmap.size': {'type': 'int'},
    'security.iommu': {'type': 'bool'},
    'security.protection.delete': {'type': 'bool'},
    'security.protection.shift': {'type': 'bool'},
    'security.secureboot': {'type': 'bool'},
    'security.sev': {'type': 'bool'},
    'security.sev.policy.es': {'type': 'bool'},
    'security.sev.session.data': {'type': 'str'},
    'security.sev.session.dh': {'type': 'str'},
    'security.syscalls.allow': {'type': 'str'},
    'security.syscalls.deny': {'type': 'str'},
    'security.syscalls.deny_compat': {'type': 'bool'},
    'security.syscalls.deny_default': {'type': 'bool'},
    'security.syscalls.intercept.bpf': {'type': 'bool'},
    'security.syscalls.intercept.bpf.devices': {'type': 'bool'},
    'security.syscalls.intercept.mknod': {'type': 'bool'},
    'security.syscalls.intercept.mount': {'type': 'bool'},
    'security.syscalls.intercept.mount.allowed': {'type': 'str'},
    'security.syscalls.intercept.mount.fuse': {'type': 'str'},
    'security.syscalls.intercept.mount.shift': {'type': 'bool'},
    'security.syscalls.intercept.sched_setscheduler': {'type': 'bool'},
    'security.syscalls.intercept.setxattr': {'type': 'bool'},
    'security.syscalls.intercept.sysinfo': {'type': 'bool'},
    'migration.stateful': {'type': 'bool'},
    'migration.incremental.memory': {'type': 'bool'},
    'migration.incremental.memory.goal': {'type': 'int'},
    'migration.incremental.memory.iterations': {'type': 'int'},
    'snapshots.expiry': {'type': 'str'},
    'snapshots.expiry.manual': {'type': 'str'},
    'snapshots.pattern': {'type': 'str'},
    'snapshots.schedule': {'type': 'str'},
    'snapshots.schedule.stopped': {'type': 'bool'},
    'nvidia.driver.capabilities': {'type': 'str'},
    'nvidia.require.cuda': {'type': 'str'},
    'nvidia.require.driver': {'type': 'str'},
    'nvidia.runtime': {'type': 'bool'},
    'raw.apparmor': {'type': 'str'},
    'raw.idmap': {'type': 'str'},
    'raw.lxc': {'type': 'str'},
    'raw.qemu': {'type': 'str'},
    'raw.qemu.conf': {'type': 'str'},
    'raw.qemu.qmp.early': {'type': 'str'},
    'raw.qemu.qmp.pre-start': {'type': 'str'},
    'raw.qemu.qmp.post-start': {'type': 'str'},
    'raw.qemu.scriptlet': {'type': 'str'},
    'raw.seccomp': {'type': 'str'},
    'agent.nic_config': {'type': 'bool'},
    'cluster.evacuate': {'type': 'str', 'choices': [
        'auto', 'live-migrate', 'migrate', 'stop', 'stateful-stop', 'force-stop',
    ]},
    'linux.kernel_modules': {'type': 'str'},
    'oci.cwd': {'type': 'str'},
    'oci.entrypoint': {'type': 'str'},
    'oci.gid': {'type': 'str'},
    'oci.uid': {'type': 'str'},
    'environment_variables': {
        'type': 'list',
        'elements': 'dict',
        'options': {
            'name': {
                'type': 'str',
                'required': True,
            },
            'value': {
                'type': 'str',
                'required': True,
            },
        },
    },
    **CLOUD_INIT_CONFIG_OPTIONS,
}
