---
incus_client_package_name: incus-client
incus_client_package_state: present
incus_client_apt_preference_name: incus-client
incus_client_apt_preference_pin: origin pkgs.zabbly.com
incus_client_apt_preference_pin_priority: 990
incus_client_user: root
incus_client_group: incus-admin
incus_client_configuration_file: config.yml
incus_client_configuration:
  default-remote: local
  remotes:
    - name: local
      addr: unix://
      protocol: incus
      public: false
    - name: images
      addr: https://images.linuxcontainers.org
      protocol: simplestreams
      public: true
