---
argument_specs:
  main:
    short_description: Ensure Incus storage volumes.
    description:
      - Ensure Incus storage volumes.
    examples: |
      - name: Ensure incus storage volumes
        hosts: incus
        tasks:
          - name: Ensure incus storage volumes
            ansible.builtin.import_role:
              name: damex.incus.incus_storage_volumes
            vars:
              incus_storage_volumes:
                - name: data
                  pool: default
                - name: media
                  pool: zfs
                  content_type: block
                  config:
                    size: "50GiB"
                - name: backups
                  pool: default
                  config:
                    snapshots.schedule: "@daily"
                    snapshots.expiry: "7d"
                - name: plexmediaserver
                  pool: local
                  targets:
                    - name: node1.example.com
                      config:
                        size: "100GiB"
                    - name: node2.example.com
    options:
      incus_storage_volumes:
        description: Storage volumes to ensure.
        type: list
        elements: dict
        options:
          name:
            description: Storage volume name.
            required: true
            type: str
          pool:
            description: Storage pool name.
            required: true
            type: str
          content_type:
            description: Storage volume content type.
            type: str
            choices:
              - filesystem
              - block
          description:
            description: Storage volume description.
            type: str
          project:
            description: Incus project scope.
            type: str
          config:
            description: Storage volume configuration options.
            type: dict
            options:
              size:
                description: Storage volume size.
                type: str
              snapshots.expiry:
                description: Automatic expiry time for snapshots.
                type: str
              snapshots.pattern:
                description: Pongo2 template for snapshot names.
                type: str
              snapshots.schedule:
                description: Cron expression for automatic snapshots.
                type: str
              block.filesystem:
                description: Filesystem type for block volumes.
                type: str
              block.mount_options:
                description: Mount options for block volumes.
                type: str
              zfs.blocksize:
                description: ZFS volume block size.
                type: str
              zfs.block_mode:
                description: ZFS volume block device mode.
                type: bool
              zfs.delegate:
                description: ZFS dataset delegation to instance.
                type: bool
              zfs.remove_snapshots:
                description: Snapshot removal on volume removal.
                type: bool
          targets:
            description: Cluster member targets for storage volume creation.
            type: list
            elements: dict
            options:
              name:
                description: Cluster member name.
                required: true
                type: str
              config:
                description: Per-member storage volume configuration options.
                type: dict
                options:
                  size:
                    description: Storage volume size.
                    type: str
          state:
            description: Storage volume desired state.
            type: str
            choices:
              - present
              - absent
      incus_storage_volumes_socket_path:
        description: Incus Unix socket path.
        type: path
      incus_storage_volumes_url:
        description: Incus server API URL.
        type: str
      incus_storage_volumes_client_cert:
        description: Client certificate content for API authentication.
        type: str
      incus_storage_volumes_client_key:
        description: Client key content for API authentication.
        type: str
      incus_storage_volumes_server_cert:
        description: Server certificate content for API verification.
        type: str
      incus_storage_volumes_client_cert_path:
        description: TLS client certificate path for API authentication.
        type: path
      incus_storage_volumes_client_key_path:
        description: TLS client key path for API authentication.
        type: path
      incus_storage_volumes_server_cert_path:
        description: TLS server certificate path for API verification.
        type: path
      incus_storage_volumes_token:
        description: Incus API authentication token.
        type: str
      incus_storage_volumes_validate_certs:
        description: TLS certificate validation.
        type: bool
      incus_storage_volumes_project:
        description: Incus project scope.
        type: str
      incus_storage_volumes_state:
        description: Storage volumes desired state.
        type: str
        choices:
          - present
          - absent
