---
incus_network_address_sets: [] # noqa: var-naming[no-role-prefix]
incus_network_address_sets_socket_path: /var/lib/incus/unix.socket
incus_network_address_sets_validate_certs: true
incus_network_address_sets_project: default
incus_network_address_sets_state: present
