---
incus_package_name: incus
incus_package_state: present
incus_service_name: incus
incus_apt_preference_name: incus
incus_apt_preference_pin: origin pkgs.zabbly.com
incus_apt_preference_pin_priority: 990
