---
- name: Ensure incus instance {{ incus_instances_instance_name }}
  damex.incus.incus_instance:
    name: "{{ incus_instances_instance_name }}"
    state: "{{ incus_instances_instance_state }}"
    source: "{{ incus_instances_instance_source | default(omit) }}"
    type: "{{ incus_instances_instance_type }}"
    project: "{{ incus_instances_instance_project }}"
    profiles: "{{ incus_instances_instance_profiles }}"
    ephemeral: "{{ incus_instances_instance_ephemeral }}"
    config: "{{ incus_instances_instance_config | default(omit) }}"
    devices: "{{ incus_instances_instance_devices | default(omit) }}"
    socket_path: "{{ incus_instances_socket_path }}"
  become: true
  when: incus_instances_cluster_info_state.cluster_members | length == 0 or 'database' in incus_instances_cluster_info_state.cluster_members[0].roles
