---
- name: Ensure incus instance {{ incus_instances_instance_name }}
  damex.incus.incus_instance:
    name: "{{ incus_instances_instance_name }}"
    state: "{{ incus_instances_instance_state }}"
    source: "{{ incus_instances_instance_source | default(omit) }}"
    type: "{{ incus_instances_instance_type }}"
    project: "{{ incus_instances_instance_project }}"
    profiles: "{{ incus_instances_instance_profiles }}"
    target: "{{ incus_instances_instance_target | default(omit) }}"
    ephemeral: "{{ incus_instances_instance_ephemeral }}"
    config: "{{ incus_instances_instance_config | default(omit) }}"
    devices: "{{ incus_instances_instance_devices | default(omit) }}"
    socket_path: "{{ incus_instances_instance_socket_path }}"
    url: "{{ incus_instances_instance_url }}"
    client_cert: "{{ incus_instances_instance_client_cert }}"
    client_key: "{{ incus_instances_instance_client_key }}"
    server_cert: "{{ incus_instances_instance_server_cert }}"
    token: "{{ incus_instances_instance_token }}"
    validate_certs: "{{ incus_instances_instance_validate_certs }}"
  no_log: "{{ incus_instances_client_key is defined or incus_instances_token is defined or (incus_instances_instance.config is defined and (('cloud-init.user-data' in incus_instances_instance.config and 'password' in incus_instances_instance.config['cloud-init.user-data']) or ('cloud-init.vendor-data' in incus_instances_instance.config and 'password' in incus_instances_instance.config['cloud-init.vendor-data']))) }}"
  become: true
  when: incus_instances_cluster_info_state.cluster_members | length == 0 or 'database' in incus_instances_cluster_info_state.cluster_members | map(attribute='roles') | first
