---
- name: Ensure incus network {{ incus_networks_network_name }}
  damex.incus.incus_network:
    name: "{{ incus_networks_network_name }}"
    state: "{{ incus_networks_network_state }}"
    type: "{{ incus_networks_network_type }}"
    description: "{{ incus_networks_network_description }}"
    project: "{{ incus_networks_network_project }}"
    config: "{{ incus_networks_network_config }}"
    socket_path: "{{ incus_networks_network_socket_path }}"
    url: "{{ incus_networks_network_url }}"
    client_cert: "{{ incus_networks_network_client_cert }}"
    client_key: "{{ incus_networks_network_client_key }}"
    server_cert: "{{ incus_networks_network_server_cert }}"
    client_cert_path: "{{ incus_networks_network_client_cert_path }}"
    client_key_path: "{{ incus_networks_network_client_key_path }}"
    server_cert_path: "{{ incus_networks_network_server_cert_path }}"
    token: "{{ incus_networks_network_token }}"
    validate_certs: "{{ incus_networks_network_validate_certs }}"
  no_log: "{{ incus_networks_client_key is defined or incus_networks_token is defined }}"
  become: true
