---
- name: Ensure incus network {{ incus_networks_network_name }}
  damex.incus.incus_network:
    name: "{{ incus_networks_network_name }}"
    state: "{{ incus_networks_network_state }}"
    type: "{{ incus_networks_network.type }}"
    project: "{{ incus_networks_network_project }}"
    config: "{{ incus_networks_network.config | default(omit) }}"
    socket_path: "{{ incus_networks_socket_path }}"
  become: true
  when: incus_networks_cluster_info_state.cluster_members | length == 0 or 'database' in incus_networks_cluster_info_state.cluster_members[0].roles
