---
- name: Ensure incus client configuration directory
  ansible.builtin.file:
    path: "{{ incus_client_configuration_directory | default(ansible_facts['user_dir'] + '/.config/incus') }}"
    state: directory
    owner: "{{ incus_client_user }}"
    group: "{{ incus_client_group }}"
    mode: "0750"
  become: true

- name: Ensure incus client configuration file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ incus_client_configuration_directory | default(ansible_facts['user_dir'] + '/.config/incus') }}/{{ incus_client_configuration_file }}"
    owner: "{{ incus_client_user }}"
    group: "{{ incus_client_group }}"
    mode: "0640"
  become: true
