---
- name: Ensure incus cluster facts
  damex.incus.incus_server_info:
    socket_path: "{{ incus_cluster_socket_path }}"
  register: incus_cluster_info_state
  become: true

- name: Ensure incus cluster primary fact
  ansible.builtin.set_fact:
    incus_cluster_primary: "{{ groups[incus_cluster_group] | first }}"
