---
- name: Ensure incus cluster facts
  damex.incus.incus_server_info:
    socket_path: "{{ incus_cluster_socket_path }}"
    url: "{{ incus_cluster_url | default(omit) }}"
    client_cert: "{{ incus_cluster_client_cert | default(omit) }}"
    client_key: "{{ incus_cluster_client_key | default(omit) }}"
    server_cert: "{{ incus_cluster_server_cert | default(omit) }}"
    client_cert_path: "{{ incus_cluster_client_cert_path | default(omit) }}"
    client_key_path: "{{ incus_cluster_client_key_path | default(omit) }}"
    server_cert_path: "{{ incus_cluster_server_cert_path | default(omit) }}"
    token: "{{ incus_cluster_token | default(omit) }}"
    validate_certs: "{{ incus_cluster_validate_certs }}"
  no_log: "{{ incus_cluster_client_key is defined or incus_cluster_token is defined }}"
  register: incus_cluster_info_state
  become: true

- name: Ensure incus cluster primary fact
  ansible.builtin.set_fact:
    incus_cluster_primary: "{{ groups[incus_cluster_group] | first }}"
