---
- name: Ensure incus cluster join
  when: inventory_hostname != incus_cluster_primary
  become: true
  block:
    - name: Ensure incus cluster member info
      damex.incus.incus_cluster_member_info:
        name: "{{ incus_cluster_cluster.server_name }}"
        socket_path: "{{ incus_cluster_socket_path }}"
        url: "{{ incus_cluster_url | default(omit) }}"
        client_cert: "{{ incus_cluster_client_cert | default(omit) }}"
        client_key: "{{ incus_cluster_client_key | default(omit) }}"
        server_cert: "{{ incus_cluster_server_cert | default(omit) }}"
        client_cert_path: "{{ incus_cluster_client_cert_path | default(omit) }}"
        client_key_path: "{{ incus_cluster_client_key_path | default(omit) }}"
        server_cert_path: "{{ incus_cluster_server_cert_path | default(omit) }}"
        token: "{{ incus_cluster_token | default(omit) }}"
        validate_certs: "{{ incus_cluster_validate_certs }}"
      no_log: "{{ incus_cluster_client_key is defined or incus_cluster_token is defined }}"
      delegate_to: "{{ incus_cluster_primary }}"
      register: incus_cluster_member_info_state
    - name: Ensure incus cluster member is joined {{ incus_cluster_cluster.server_name }}
      when: incus_cluster_member_info_state.cluster_members | length == 0
      block:
        - name: Ensure incus cluster member token {{ incus_cluster_cluster.server_name }}
          damex.incus.incus_cluster_member:
            name: "{{ incus_cluster_cluster.server_name }}"
            state: joined
            socket_path: "{{ incus_cluster_socket_path }}"
            url: "{{ incus_cluster_url | default(omit) }}"
            client_cert: "{{ incus_cluster_client_cert | default(omit) }}"
            client_key: "{{ incus_cluster_client_key | default(omit) }}"
            server_cert: "{{ incus_cluster_server_cert | default(omit) }}"
            client_cert_path: "{{ incus_cluster_client_cert_path | default(omit) }}"
            client_key_path: "{{ incus_cluster_client_key_path | default(omit) }}"
            server_cert_path: "{{ incus_cluster_server_cert_path | default(omit) }}"
            token: "{{ incus_cluster_token | default(omit) }}"
            validate_certs: "{{ incus_cluster_validate_certs }}"
          delegate_to: "{{ incus_cluster_primary }}"
          register: incus_cluster_member_token_state
          no_log: true
        - name: Ensure incus cluster is joined {{ incus_cluster_cluster.server_name }}
          damex.incus.incus_server:
            init: true
            config: "{{ incus_cluster_config }}"
            cluster: "{{ incus_cluster_cluster | combine({'cluster_address': hostvars[incus_cluster_primary].incus_cluster_cluster.server_address, 'cluster_token': incus_cluster_member_token_state.join_token}) }}"
            socket_path: "{{ incus_cluster_socket_path }}"
          no_log: true
