---
argument_specs:
  main:
    short_description: Ensure Incus repository.
    description:
      - Ensure the Incus repository.
    examples: |
      - name: Ensure incus repository
        hosts: incus
        tasks:
          - name: Ensure incus repository
            ansible.builtin.import_role:
              name: damex.incus.incus_repository

      - name: Ensure incus LTS repository
        hosts: incus
        tasks:
          - name: Ensure incus LTS repository
            ansible.builtin.import_role:
              name: damex.incus.incus_repository
            vars:
              incus_repository_apt_repository_url: https://pkgs.zabbly.com/incus/lts-6.0
    options:
      incus_repository_apt_key_id:
        type: str
        description: GPG key ID for the Incus APT repository.
      incus_repository_apt_key_url:
        type: str
        description: URL of the GPG key for the Incus APT repository.
      incus_repository_apt_repository_name:
        type: str
        description: Name of the Incus APT repository source entry.
      incus_repository_apt_repository_url:
        type: str
        description: Base URL of the Incus APT repository.
      incus_repository_apt_repository_distribution:
        type: str
        description: Distribution component override for the APT repository.
      incus_repository_apt_repository_components:
        type: list
        elements: str
        description: List of APT repository components to enable.
      incus_repository_yum_repository_name:
        type: str
        description: Unique repository ID for the Incus YUM repository.
      incus_repository_yum_repository_baseurl:
        type: str
        description: URL to the directory where the Incus YUM repository repodata is located.
      incus_repository_yum_repository_gpgcheck:
        type: bool
        description: GPG signature check for the Incus YUM repository.
      incus_repository_yum_repository_gpgkey:
        type: str
        description: URL pointing to the ASCII-armored GPG key file for the Incus YUM repository.
