---
- name: Ensure incus image {{ incus_images_image_name }}
  damex.incus.incus_image:
    alias: "{{ incus_images_image_alias }}"
    source: "{{ incus_images_image_source }}"
    project: "{{ incus_images_image_project }}"
    type: "{{ incus_images_image_type }}"
    copy_aliases: "{{ incus_images_image_copy_aliases }}"
    state: "{{ incus_images_image_state }}"
    socket_path: "{{ incus_images_image_socket_path }}"
    url: "{{ incus_images_image_url }}"
    client_cert: "{{ incus_images_image_client_cert }}"
    client_key: "{{ incus_images_image_client_key }}"
    server_cert: "{{ incus_images_image_server_cert }}"
    token: "{{ incus_images_image_token }}"
    validate_certs: "{{ incus_images_image_validate_certs }}"
