---
- name: Ensure incus image {{ incus_images_image_name }}
  damex.incus.incus_image:
    alias: "{{ incus_images_image_alias }}"
    source: "{{ incus_images_image_source }}"
    project: "{{ incus_images_image_project }}"
    type: "{{ incus_images_image_type }}"
    copy_aliases: "{{ incus_images_image_copy_aliases }}"
    state: "{{ incus_images_image_state }}"
    socket_path: "{{ incus_images_socket_path }}"
