---
- name: Ensure incus image {{ incus_images_image_name }}
  damex.incus.incus_image:
    alias: "{{ incus_images_image_alias }}"
    source: "{{ incus_images_image_source }}"
    project: "{{ incus_images_image_project }}"
    type: "{{ incus_images_image_type }}"
    copy_aliases: "{{ incus_images_image_copy_aliases }}"
    auto_update: "{{ incus_images_image_auto_update }}"
    public: "{{ incus_images_image_public }}"
    source_server: "{{ incus_images_image_source_server }}"
    source_protocol: "{{ incus_images_image_source_protocol }}"
    state: "{{ incus_images_image_state }}"
    socket_path: "{{ incus_images_image_socket_path }}"
    url: "{{ incus_images_image_url }}"
    client_cert: "{{ incus_images_image_client_cert }}"
    client_key: "{{ incus_images_image_client_key }}"
    server_cert: "{{ incus_images_image_server_cert }}"
    client_cert_path: "{{ incus_images_image_client_cert_path }}"
    client_key_path: "{{ incus_images_image_client_key_path }}"
    server_cert_path: "{{ incus_images_image_server_cert_path }}"
    token: "{{ incus_images_image_token }}"
    validate_certs: "{{ incus_images_image_validate_certs }}"
  no_log: "{{ incus_images_client_key is defined or incus_images_token is defined }}"
  become: true
