---
- name: Ensure incus
  tags:
    - incus
  block:
    - name: Ensure incus facts
      ansible.builtin.import_tasks: facts.yml
    - name: Ensure incus apt preference
      ansible.builtin.import_tasks: apt_preference.yml
    - name: Ensure incus package
      ansible.builtin.import_tasks: package.yml
    - name: Ensure incus systemd
      ansible.builtin.import_tasks: systemd.yml
    - name: Ensure incus socket symlinks
      ansible.builtin.import_tasks: socket.yml
