---
- name: Ensure incus qemu symlink
  ansible.builtin.file:
    src: /usr/libexec/qemu-kvm
    dest: /usr/local/bin/qemu-system-{{ ansible_facts['architecture'] }}
    state: link
  become: true
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] != "Fedora"
    - "'qemu-kvm-core' in ansible_facts.packages"
